trigger: 
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.23.3'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Bash@3
  displayName: Tests
  inputs:
    targetType: inline
    script: |
      # Get tools for converting Go's test reports
      go get -u github.com/jstemmer/go-junit-report 2>&1
      go get -u github.com/axw/gocov/gocov 2>&1
      go get -u github.com/AlekSi/gocov-xml 2>&1

      # Run Go tests and turn output into JUnit test result format
      go test . -v -coverprofile=coverage.txt -covermode count 2>&1 | $HOME/go/bin/go-junit-report > report.xml
      rc=${PIPESTATUS[0]} # Get result code of `go test`
      # Show files
      ls *.xml
      
      # Convert coverage file into XML
      gocov convert coverage.txt > coverage.json
      gocov-xml < coverage.json > coverage.xml

      # Check if `go test` had an error
      if [ $rc -ne 0 ]; then
        # Let script fail by writing to stderr
        >&2 echo "Tests failed"
      fi
- task: Go@0
  displayName: Fuzz 
  inputs:
    command: 'test'
    arguments: '-v -fuzz=Fuzz -fuzztime 2m'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: "*report*.xml"   
    searchFolder: "$(Build.SourcesDirectory)"
    failTaskOnFailedTests: true
    testRunTitle: "Go Tests"
- task: PublishCodeCoverageResults@2
  inputs:
   summaryFileLocation: "coverage.xml"
   pathToSources: "$(System.DefaultWorkingDirectory)"
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop

     